# Generated by Django 5.0.1 on 2024-01-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight_in_grams',
            field=models.PositiveIntegerField(default=0, verbose_name='Вес продукта в граммах'),
        ),
    ]
